version: "3.7"

services:
  #  web:
  #    image: postgres:11-alpine
  #    ports:
  #      - 5432:5432
  #    environment:
  #      - POSTGRES_PASSWORD=$DB_PASSWORD
  #      - POSTGRES_DB=$DB_NAME
  #      - POSTGRES_USER=$DB_USER
  #    env_file:
  #      - .env

  backend:
    build: .
    volumes:
      - .:/code/
      - node_modules:/code/node_modules
    ports:
      - 3000:3000

volumes:
    node_modules:
