version: "3.7"

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
    env_file:
      - .env

  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./:/code/
