version: "3.7"

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USERNAME
    env_file:
      - .env

  backend:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code/
      - node_modules:/code/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_PORT=5432
      - DB_HOST=db

volumes:
    node_modules:
